### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by najam828** [KitwareMedical/dicom-exporter#10]
I am trying to create a .vtkjs file on a Ubuntu machine from a series of dicom which is working fine on the window machines but I need to do this in Ubuntu. But whenever I tried to run the command
 (dicom-exporter /var/Python/3D_render/Uploads/16022023043513  /var/Python/3D_rendering_new/static/test.vtkjs) in the terminal. I am getting an error (Illegal instruction (core dumped)). I have already installed all the dependencies by doing ( pip3 install . ). But nothing is happing. I am just stuck there? 
I really need help here.
Thanks in advance.

**Comment by khanhhoaa19** [comment]
I'm having trouble running it on Windows. When I try to render the VTI file, I encounter an error stating: 'dicom-exporter' is not recognized as an internal or external command, operable program or batch file, despite having executed the 'pip install .' command.

**Comment by finetjul** [comment]
@khanhhoaa19 it looks that your problem is different from @najam828.

Please create a separate issue.

**Comment by najam828** [comment]
Well I had already solved the issue along time ago and I really forgot to close this issue. My issue was due to ram when I upgrade the pc with more ram then the program started working just fine.
Thanks!
